meta_product_name: "Exceltips"
meta_title: "2 HEURES, c'est ce qu'il vous faut pour devenir productif sur Excel"
meta_description: "La formation Exceltips, c'est la promesse d'apprendre uniquement l'essentiel. Et rien d'autre."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
